#!/bin/sh
set -e

PREREQ=""
prereqs() { echo "$PREREQ"; }

case "$1" in
    prereqs)
        prereqs
        exit 0
        ;;
esac

. /usr/share/initramfs-tools/hook-functions

# Ensure the keyscript is present in the initramfs.
copy_exec /usr/local/sbin/cryptroot-usb-askpass /usr/local/sbin/cryptroot-usb-askpass
